### ISSUE TITLE
Cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by MoffKalast** [MycroftAI/mimic1#188] opened 2019-12-25 21:44 UTC
I've just compiled the codebase on Ubuntu 16.04, and afterwards did the following:

` ./mimic -t TEXT`

Which worked fine.

` ./mimic -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow."`

Which also worked as it should. Then I ran:

`./mimic -t "Hello" -voice http://www.festvox.org/flite/packed/flite-2.0/voices/cmu_us_ksp.flitevox`

Which hung, as the file was probably not found. So I cancelled that and attempted to use the executable again using any of the commands listed on the examples page which now gives me the following:

` /mimic: cannot execute binary file: Exec format error`

How in the world did running that command just brake the entire thing? The only related information about that error is about people running ARM code on x86 or vice versa which doesn't even remotely make sense.

I've tried rebooting and setting other voices as parameters, redid a chmod 777 to no avail. The make check tests somehow still pass. Do they actually check anything?

Any ideas?

**Comment by ghost** [comment] 2021-09-14 20:58
i tested this on current code in Ubuntu 20.04, cannot reproduce

**Comment by krisgesling** [comment] 2021-09-17 21:23
Thanks @NESC1US it may have been fixed in the interim so I'll close it.

**Closed by krisgesling** 2021-09-17 21:23 UTC
